### ISSUE TITLE
Entity Includes

### ISSUE THREAD

**Issue by ghost** [imranbaloch/ASPNETIdentityWithOnion#15]
Hello. This is an awesome project and it has inspired us to modify ours a bit.
I do have one question. How do you address the .Include() issue? Your repository pattern uses only one interface.

We had to introduce other interfaces to extend base repository. 
For example we need to include references to an Account table because I wanted to know who created this Person 'John Doe' in Person table.

Also, where do you create Data Mappers?

thank you

**Comment by dmdb0101** [comment]
never mind. we figured it out.
The only difference from ours is we created multiple services because we placed the logic there.
Reason is to avoid rewriting business logic.
For example, when creating a product (with validation). If we placed it in controller, we have to have validation logic and create product logic. But what if we had a native desktop app that does the same thing, then if we took this approach, we would have to write the product with validation code again.
Same goes client decides we create web api, then we have to do the same thing.
